version: "3.9"

services:
  send_config_api:
    build: .
    container_name: send_config_api

    # ───────── Variables ─────────
    env_file: .env
    environment:
      - APP_PORT=${APP_PORT}

    # ───────── Puertos ───────────
    ports:
      - "${HOST_PORT:-8080}:${APP_PORT}"

    # ───────── Persistencia ──────
    volumes:
      - ./logs:/app/logs

    # ───────── Red a usar ────────
    networks:
      - omarsa-docker         # ← aquí la asociamos

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${APP_PORT}/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s

# ──────────────────────────────────────────
# Redes
# ──────────────────────────────────────────
networks:
  omarsa-docker:
    external: true            # ← declara que ya existe fuera de compose
